"""
generate_config.py
robot_config.yaml から include/Config.h と include/UrdfConfig.h を自動生成します。

各名前空間セクションを専用の関数で生成することで、
可読性・テスト性・メンテナンス性を向上させています。
"""
import os
import yaml


# ── ユーティリティ ────────────────────────────────────────────────────────

def _bool(b: bool) -> str:
    """Python の bool を C++ のリテラル文字列に変換する"""
    return "true" if b else "false"


# ── UrdfConfig.h セクション ───────────────────────────────────────────────

def _gen_urdf_config(c: dict) -> str:
    return f"""#ifndef URDF_CONFIG_H
#define URDF_CONFIG_H

// =============================================================================
//   AUTO-GENERATED ON-SHAPE DESIGN DIMENSIONS (DO NOT EDIT)
//   Generated by generate_config.py from robot_config.yaml
// =============================================================================

namespace RobotConfig {{
    // 脚のパーツの長さ (mm)
    const float L1 = {c['L1']:.2f}f;  // 肩の回転軸から膝の回転軸まで
    const float L2 = {c['L2']:.2f}f;  // 膝の回転軸から足先まで

    // 各脚の肩サーボの取り付け位置 (ボディ中心からのX, Y座標 mm)
    const float FR_OFFSET_X = {c['FR_OFFSET_X']:.2f}f;
    const float FR_OFFSET_Y = {c['FR_OFFSET_Y']:.2f}f;

    const float FL_OFFSET_X = {c['FL_OFFSET_X']:.2f}f;
    const float FL_OFFSET_Y = {c['FL_OFFSET_Y']:.2f}f;

    const float BR_OFFSET_X = {c['BR_OFFSET_X']:.2f}f;
    const float BR_OFFSET_Y = {c['BR_OFFSET_Y']:.2f}f;

    const float BL_OFFSET_X = {c['BL_OFFSET_X']:.2f}f;
    const float BL_OFFSET_Y = {c['BL_OFFSET_Y']:.2f}f;
}}

#endif // URDF_CONFIG_H
"""


# ── Config.h 各セクション ─────────────────────────────────────────────────

def _gen_hardware_section(c: dict) -> str:
    """HardwareConfig 名前空間および FIRMWARE_VERSION マクロを生成する"""
    return (
        f'// ファームウェアバージョン (文字列連結で F() マクロと組み合わせ可能)\n'
        f'#define FIRMWARE_VERSION "{c["FIRMWARE_VERSION"]}"\n'
        f'\n'
        f'namespace HardwareConfig {{\n'
        f'    const int     ULTRASONIC_TRIG = {c["ULTRASONIC_TRIG"]};\n'
        f'    const int     ULTRASONIC_ECHO = {c["ULTRASONIC_ECHO"]};\n'
        f'    const uint8_t PCA9685_ADDR    = 0x{c["PCA9685_ADDR"]:02X};  // PCA9685 I2Cアドレス\n'
        f'}}'
    )


def _gen_servo_section(c: dict) -> str:
    """ServoConfig 名前空間を生成する"""
    return f"""namespace ServoConfig {{
    const int SERVO_FREQ = {c['SERVO_FREQ']};

    enum Channel {{
        FR_HIP = {c['FR_HIP_CHANNEL']}, FR_KNEE = {c['FR_KNEE_CHANNEL']},
        BL_HIP = {c['BL_HIP_CHANNEL']}, BL_KNEE = {c['BL_KNEE_CHANNEL']},
        FL_HIP = {c['FL_HIP_CHANNEL']}, FL_KNEE = {c['FL_KNEE_CHANNEL']},
        BR_HIP = {c['BR_HIP_CHANNEL']}, BR_KNEE = {c['BR_KNEE_CHANNEL']},
        SENSOR = {c['SENSOR_SERVO_CHANNEL']},
        COUNT  = 9
    }};

    const char* const JOINT_NAMES[] = {{
        "FR_HIP", "FR_KNEE",
        "BL_HIP", "BL_KNEE",
        "FL_HIP", "FL_KNEE",
        "BR_HIP", "BR_KNEE",
        "SENSOR"
    }};

    const bool INVERT_FR_HIP  = {_bool(c['INVERT_FR_HIP'])};
    const bool INVERT_FR_KNEE = {_bool(c['INVERT_FR_KNEE'])};
    const bool INVERT_BL_HIP  = {_bool(c['INVERT_BL_HIP'])};
    const bool INVERT_BL_KNEE = {_bool(c['INVERT_BL_KNEE'])};
    const bool INVERT_FL_HIP  = {_bool(c['INVERT_FL_HIP'])};
    const bool INVERT_FL_KNEE = {_bool(c['INVERT_FL_KNEE'])};
    const bool INVERT_BR_HIP  = {_bool(c['INVERT_BR_HIP'])};
    const bool INVERT_BR_KNEE = {_bool(c['INVERT_BR_KNEE'])};

    const float FR_HIP_TRIM  = {c['FR_HIP_TRIM']:.1f}f;
    const float FR_KNEE_TRIM = {c['FR_KNEE_TRIM']:.1f}f;
    const float BL_HIP_TRIM  = {c['BL_HIP_TRIM']:.1f}f;
    const float BL_KNEE_TRIM = {c['BL_KNEE_TRIM']:.1f}f;
    const float FL_HIP_TRIM  = {c['FL_HIP_TRIM']:.1f}f;
    const float FL_KNEE_TRIM = {c['FL_KNEE_TRIM']:.1f}f;
    const float BR_HIP_TRIM  = {c['BR_HIP_TRIM']:.1f}f;
    const float BR_KNEE_TRIM = {c['BR_KNEE_TRIM']:.1f}f;

    const int   PULSE_MIN      = {c['PULSE_MIN']};
    const int   PULSE_MAX      = {c['PULSE_MAX']};
    const float NEUTRAL_ANGLE  = {c['NEUTRAL_ANGLE']:.1f}f;

    const float FR_HIP_MIN  = {c['FR_HIP_MIN']:.1f}f;
    const float FR_HIP_MAX  = {c['FR_HIP_MAX']:.1f}f;
    const float FR_KNEE_MIN = {c['FR_KNEE_MIN']:.1f}f;
    const float FR_KNEE_MAX = {c['FR_KNEE_MAX']:.1f}f;

    const float BL_HIP_MIN  = {c['BL_HIP_MIN']:.1f}f;
    const float BL_HIP_MAX  = {c['BL_HIP_MAX']:.1f}f;
    const float BL_KNEE_MIN = {c['BL_KNEE_MIN']:.1f}f;
    const float BL_KNEE_MAX = {c['BL_KNEE_MAX']:.1f}f;

    const float FL_HIP_MIN  = {c['FL_HIP_MIN']:.1f}f;
    const float FL_HIP_MAX  = {c['FL_HIP_MAX']:.1f}f;
    const float FL_KNEE_MIN = {c['FL_KNEE_MIN']:.1f}f;
    const float FL_KNEE_MAX = {c['FL_KNEE_MAX']:.1f}f;

    const float BR_HIP_MIN  = {c['BR_HIP_MIN']:.1f}f;
    const float BR_HIP_MAX  = {c['BR_HIP_MAX']:.1f}f;
    const float BR_KNEE_MIN = {c['BR_KNEE_MIN']:.1f}f;
    const float BR_KNEE_MAX = {c['BR_KNEE_MAX']:.1f}f;

    const float SENSOR_MIN  = {c['SENSOR_MIN']:.1f}f;
    const float SENSOR_MAX  = {c['SENSOR_MAX']:.1f}f;
}}"""


def _gen_robot_section(c: dict) -> str:
    """RobotConfig 名前空間 (スタンスオフセット) を生成する"""
    return f"""namespace RobotConfig {{
    const float STANCE_OFFSET_X = {c['STANCE_OFFSET_X']:.1f}f;
    const float STANCE_OFFSET_Y = {c['STANCE_OFFSET_Y']:.1f}f;
}}"""


def _gen_gait_section(c: dict) -> str:
    """GaitConfig 名前空間を生成する"""
    return f"""namespace GaitConfig {{
    const float DEFAULT_Z         = {c['DEFAULT_Z']:.1f}f;
    const float STANCE_PULLDOWN_Z = {c['STANCE_PULLDOWN_Z']:.1f}f;
    const float STEP_HEIGHT       = {c['STEP_HEIGHT']:.1f}f;
    const float STEP_LENGTH       = {c['STEP_LENGTH']:.1f}f;
    const int   CYCLE_TIME        = {c['CYCLE_TIME']};

    const float BODY_SHIFT_X   = {c['BODY_SHIFT_X']:.1f}f;
    const float BODY_SHIFT_Y   = {c['BODY_SHIFT_Y']:.1f}f;
    const float SWING_RATIO    = {c['SWING_RATIO']:.2f}f;
    const float LERP_RATE      = {c['LERP_RATE']:.2f}f;
    const float HEADING_ANGLE  = {c['HEADING_ANGLE']:.1f}f;

    const float STRIDE_X_DIV   = {c['STRIDE_X_DIV']:.1f}f;
    const float STRIDE_Y_DIV   = {c['STRIDE_Y_DIV']:.1f}f;
    const float STRIDE_ROT_DIV = {c['STRIDE_ROT_DIV']:.1f}f;
    const int   LEG_COUNT      = 4;     // 脚数 (固定値)
}}"""


def _gen_control_section(c: dict) -> str:
    """ControlConfig 名前空間を生成する"""
    return f"""namespace ControlConfig {{
    const float MOVE_SPEED            = {c['MOVE_SPEED']:.1f}f;
    const float TURN_SPEED            = {c['TURN_SPEED']:.1f}f;
    const int   SENSOR_CHECK_INTERVAL = {c['SENSOR_CHECK_INTERVAL']};
    const int   LOG_INTERVAL          = {c['LOG_INTERVAL']};
    const int   INPUT_TIMEOUT_MS      = {c.get('INPUT_TIMEOUT_MS', 200)};  // 入力なしで停止までのタイムアウト (ms)
    const float OBSTACLE_DETECTION_DIST = {c.get('OBSTACLE_DETECTION_DIST', 30.0):.1f}f;  // 前方障害物検知距離 (cm)
    const float OBSTACLE_CLEARANCE_DIST = {c.get('OBSTACLE_CLEARANCE_DIST', 40.0):.1f}f;  // 側方・後方障害物クリア判定距離 (cm)
    const int   AUTO_FORWARD_FINAL_MS   = {c.get('AUTO_FORWARD_FINAL_MS', 1500)}; // 回避後の直進時間 (ms)
    const float ROUGH_STEP_HEIGHT       = {c.get('ROUGH_STEP_HEIGHT', 90.0):.1f}f;  // 不整地モード時の足上げ高さ (mm)
    const int   ROUGH_CYCLE_TIME        = {c.get('ROUGH_CYCLE_TIME', 2500)};      // 不整地モード時の歩行周期時間 (ms)
    const bool  SENSOR_SERVO_ENABLED    = {_bool(c.get('SENSOR_SERVO_ENABLED', False))}; // 首振りサーボ有効化フラグ
    const int   AUTO_FORWARD_SIDE_MS    = {c.get('AUTO_FORWARD_SIDE_MS', 2000)};   // 横移動（前進）する時間 (ms)
}}"""


def _gen_imupid_section(c: dict) -> str:
    """ImuPidConfig 名前空間を生成する"""
    return (
        f'namespace ImuPidConfig {{\n'
        f'    const uint8_t BNO055_ADDR    = 0x{c["BNO055_ADDR"]:02X};  // AD0=LOW: 0x28, AD0=HIGH: 0x29\n'
        f'    const bool    ENABLED        = {_bool(c["HEADING_PID_ENABLED"])};\n'
        f'    const float   KP             = {c["HEADING_PID_KP"]:.4f}f;\n'
        f'    const float   KI             = {c["HEADING_PID_KI"]:.4f}f;\n'
        f'    const float   KD             = {c["HEADING_PID_KD"]:.4f}f;\n'
        f'    const float   MAX_CORRECTION = {c["HEADING_PID_MAX_CORRECTION"]:.2f}f;\n'
        f'    const float   TURN_DEAD      = {c["HEADING_PID_TURN_DEAD"]:.2f}f;\n'
        f'}}'
    )


# ── エントリポイント ──────────────────────────────────────────────────────

def generate_config_h(c: dict) -> str:
    """各セクションを組み合わせて Config.h の全テキストを返す"""
    sections = [
        "#ifndef CONFIG_H",
        "#define CONFIG_H",
        "",
        "#include <Arduino.h>",
        "",
        "/**",
        " * =============================================================================",
        " *   ROBOT CONFIGURATION (AUTO-GENERATED FROM robot_config.yaml - DO NOT EDIT DIRECTLY)",
        " * =============================================================================",
        " */",
        "",
        _gen_hardware_section(c),
        "",
        _gen_servo_section(c),
        "",
        '#include "UrdfConfig.h"',
        "",
        _gen_robot_section(c),
        "",
        _gen_gait_section(c),
        "",
        _gen_control_section(c),
        "",
        _gen_imupid_section(c),
        "",
        "#endif",
        "",
    ]
    return "\n".join(sections)


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    config_path = os.path.join(script_dir, "..", "robot_config.yaml")

    with open(config_path, "r", encoding="utf-8") as f:
        c = yaml.safe_load(f)

    include_dir = os.path.join(script_dir, "..", "include")
    os.makedirs(include_dir, exist_ok=True)

    urdf_path = os.path.join(include_dir, "UrdfConfig.h")
    with open(urdf_path, "w", encoding="utf-8") as f:
        f.write(_gen_urdf_config(c))
    print("✓ Generated include/UrdfConfig.h")

    config_h_path = os.path.join(include_dir, "Config.h")
    with open(config_h_path, "w", encoding="utf-8") as f:
        f.write(generate_config_h(c))
    print("✓ Generated include/Config.h")


if __name__ == "__main__":
    main()
