#ifndef URDF_CONFIG_H
#define URDF_CONFIG_H

// =============================================================================
//   AUTO-GENERATED ON-SHAPE DESIGN DIMENSIONS (DO NOT EDIT)
//   Generated by generate_config.py from robot_config.yaml
// =============================================================================

namespace RobotConfig {
    // 脚のパーツの長さ (mm)
    const float L1 = 68.56f;  // 肩の回転軸から膝の回転軸まで
    const float L2 = 126.00f;  // 膝の回転軸から足先まで

    // 各脚の肩サーボの取り付け位置 (ボディ中心からのX, Y座標 mm)
    const float FR_OFFSET_X = 38.00f;
    const float FR_OFFSET_Y = 38.00f;

    const float FL_OFFSET_X = 38.00f;
    const float FL_OFFSET_Y = -38.00f;

    const float BR_OFFSET_X = -38.00f;
    const float BR_OFFSET_Y = 38.00f;

    const float BL_OFFSET_X = -38.00f;
    const float BL_OFFSET_Y = -38.00f;
}

#endif // URDF_CONFIG_H
